# Generated by Django 6.0.3 on 2026-04-07 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analises', '0001_initial'),
        ('documentos', '0001_initial'),
        ('licitacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analise',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises', to='documentos.documento'),
        ),
        migrations.AddField(
            model_name='analise',
            name='licitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises', to='licitacoes.licitacao'),
        ),
        migrations.AddField(
            model_name='analise',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises_responsaveis', to=settings.AUTH_USER_MODEL),
        ),
    ]
