# Generated by Django 6.0.3 on 2026-04-08 02:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseExecucaoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tipo_tarefa', models.CharField(choices=[('resumo', 'Resumo'), ('extracao', 'Extracao'), ('parecer', 'Parecer'), ('comparacao', 'Comparacao'), ('checklist', 'Checklist')], max_length=32)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_processamento', 'Em processamento'), ('concluido', 'Concluido'), ('falhou', 'Falhou')], default='pendente', max_length=32)),
                ('payload_entrada', models.JSONField(blank=True, default=dict)),
                ('resultado_payload', models.JSONField(blank=True, default=dict)),
                ('mensagem_erro', models.TextField(blank=True)),
                ('solicitada_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('iniciada_em', models.DateTimeField(blank=True, null=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('identificador_task', models.CharField(blank=True, max_length=255)),
                ('modelo_utilizado', models.CharField(blank=True, max_length=128)),
                ('response_id', models.CharField(blank=True, max_length=255)),
                ('tentativas', models.PositiveSmallIntegerField(default=0)),
                ('analise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes_ia', to='analises.analise')),
            ],
            options={
                'verbose_name': 'Execucao de IA',
                'verbose_name_plural': 'Execucoes de IA',
                'ordering': ('-solicitada_em', '-created_at'),
                'indexes': [models.Index(fields=['analise', 'tipo_tarefa', 'status'], name='analises_an_analise_07ebac_idx'), models.Index(fields=['tipo_tarefa', 'solicitada_em'], name='analises_an_tipo_ta_423e30_idx'), models.Index(fields=['identificador_task'], name='analises_an_identif_b73cf8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status__in', ['pendente', 'em_processamento'])), fields=('analise', 'tipo_tarefa'), name='uniq_execucao_ia_ativa_por_analise_e_tipo')],
            },
        ),
    ]
