# Generated by Django 6.0.3 on 2026-04-08 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def popular_versoes_execucao_ia(apps, schema_editor):
    AnaliseExecucaoIA = apps.get_model("analises", "AnaliseExecucaoIA")
    execucoes = AnaliseExecucaoIA._base_manager.order_by(
        "analise_id",
        "tipo_tarefa",
        "solicitada_em",
        "created_at",
        "id",
    )
    contador_por_chave = {}
    for execucao in execucoes.iterator():
        chave = (execucao.analise_id, execucao.tipo_tarefa)
        contador_por_chave[chave] = contador_por_chave.get(chave, 0) + 1
        execucao.versao = contador_por_chave[chave]
        execucao.save(update_fields=["versao", "updated_at"])


def reverter_versoes_execucao_ia(apps, schema_editor):
    AnaliseExecucaoIA = apps.get_model("analises", "AnaliseExecucaoIA")
    AnaliseExecucaoIA._base_manager.update(versao=1)


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0003_analiseexecucaoia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analiseexecucaoia',
            options={'ordering': ('-solicitada_em', '-versao', '-created_at'), 'verbose_name': 'Execucao de IA', 'verbose_name_plural': 'Execucoes de IA'},
        ),
        migrations.AddField(
            model_name='analiseexecucaoia',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execucoes_ia_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analiseexecucaoia',
            name='erro_detalhe_interno',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='analiseexecucaoia',
            name='reprocessamento_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reprocessamentos', to='analises.analiseexecucaoia'),
        ),
        migrations.AddField(
            model_name='analiseexecucaoia',
            name='resultado_bruto',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='analiseexecucaoia',
            name='versao',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(
            popular_versoes_execucao_ia,
            reverter_versoes_execucao_ia,
        ),
        migrations.AddIndex(
            model_name='analiseexecucaoia',
            index=models.Index(fields=['analise', 'tipo_tarefa', 'versao'], name='analises_an_analise_eedf15_idx'),
        ),
        migrations.AddConstraint(
            model_name='analiseexecucaoia',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('analise', 'tipo_tarefa', 'versao'), name='uniq_execucao_ia_versao_por_analise_e_tipo'),
        ),
    ]
