# Generated by Django 6.0.3 on 2026-04-07 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255)),
                ('razao_social', models.CharField(blank=True, max_length=255)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('site', models.URLField(blank=True)),
                ('ativa', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ('nome',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('cnpj__isnull', False), models.Q(('cnpj', ''), _negated=True), ('deleted_at__isnull', True)), fields=('cnpj',), name='uniq_empresa_cnpj_ativo_quando_preenchido')],
            },
        ),
        migrations.CreateModel(
            name='EnderecoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=255)),
                ('bairro', models.CharField(blank=True, max_length=120)),
                ('cidade', models.CharField(max_length=120)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(blank=True, max_length=12)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Endereço da empresa',
                'verbose_name_plural': 'Endereços das empresas',
            },
        ),
        migrations.CreateModel(
            name='ContatoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=255)),
                ('cargo', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('principal', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Contato da empresa',
                'verbose_name_plural': 'Contatos das empresas',
                'ordering': ('nome',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('principal', True), ('deleted_at__isnull', True)), fields=('empresa',), name='uniq_contato_principal_ativo_por_empresa')],
            },
        ),
    ]
