# Generated by Django 6.0.3 on 2026-04-07 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licitacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='documentos/licitacoes/%Y/%m/')),
                ('tipo', models.CharField(choices=[('edital', 'Edital'), ('proposta', 'Proposta'), ('habilitacao', 'Habilitacao'), ('contrato', 'Contrato'), ('outros', 'Outros')], default='outros', max_length=32)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('validado', 'Validado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=32)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True)),
                ('licitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='licitacoes.licitacao')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ('-data_upload',),
            },
        ),
    ]
