# Generated by Django 6.0.3 on 2026-04-07 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('numero', models.CharField(max_length=120)),
                ('objeto', models.TextField()),
                ('orgao', models.CharField(max_length=255)),
                ('modalidade', models.CharField(choices=[('pregao', 'Pregao'), ('concorrencia', 'Concorrencia'), ('dispensa', 'Dispensa'), ('inexigibilidade', 'Inexigibilidade'), ('tomada_de_precos', 'Tomada de precos'), ('outros', 'Outros')], default='outros', max_length=32)),
                ('situacao', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_analise', 'Em analise'), ('em_andamento', 'Em andamento'), ('encerrada', 'Encerrada'), ('cancelada', 'Cancelada')], default='rascunho', max_length=32)),
                ('data_abertura', models.DateField(blank=True, null=True)),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('link_externo', models.URLField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('ativa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licitacoes', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Licitacao',
                'verbose_name_plural': 'Licitacoes',
                'ordering': ('-data_abertura', 'numero'),
            },
        ),
    ]
